title: "Juan de Dios Rojas Olvera"
email: "jdrojaso@astro.unam.mx"
description: "PhD en cosmología, machine learning y lentes gravitacionales."
baseurl: ""
url: "https://juanddiosrojas.github.io"
markdown: kramdown
permalink: pretty
